# This is a basic workflow to help you get started with Actions

name: Docker Build (default)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, docker-swarm ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker-default:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Preliminaries
      run: |
        git config pull.ff only
        cat /proc/cpuinfo

    - name: Generate Dockerfile
      run: ./generate-Dockerfile.sh

    - name: Build Image
      run: docker build -t gupyter/datascience-notebook .build/  # will take a while

    - name: Quickstart Entrypoint Script
      run: ./start-local.sh -p 8848 

    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: gupyter
        password: ${{ secrets.DOCKER_PASS }}

    - name: Push to Dockerhub
      run: docker push gupyter/datascience-notebook
